### ISSUE TITLE
NFT not working

### ISSUE THREAD

**Issue by kalwalt** [kalwalt/webarkit-OCVT#3]
Trying to collect all the informations to solve NFT tracking. I will report here my result and findings.

**Comment by kalwalt** [comment]
working on this branch https://github.com/kalwalt/webarkit-OCVT/tree/improving-nft

**Comment by kalwalt** [comment]
Compiling libs without DEBUG enabled i got any error, but enabling Debug instead i get a memory access out of bounds

**Comment by kalwalt** [comment]
This is the error: 

```
Uncaught (in promise) RuntimeError: memory access out of bounds
    at WebARKitTrackableNFT::setNFTScale(float) (041012ea:0x10b8e)
    at WebARKitTrackerNFT::newTrackable(std::__2::vector<std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >, std::__2::allocator<std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> > > >) (041012ea:0x13752)
    at WebARKitController::addTrackable(std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> > const&) (041012ea:0x2b38d)
    at arwAddTrackable (041012ea:0x1a448)
    at addTrackable(std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >) (041012ea:0x6d52)
    at emscripten::internal::Invoker<int, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> > >::invoke(int (*)(std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >), emscripten::internal::BindingType<std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >, void>::'unnamed'*) (041012ea:0xcc51)
    at WebARKit.addTrackable (eval at new_ (webarkit_ES6_wasm.js:1:1), <anonymous>:8:10)
    at WebARKitController._callee4$ (WebARKitController.ts:513:47)
    at tryCatch (runtime.js:63:40)
    at Generator.invoke [as _invoke] (runtime.js:294:22)
```
